from pyannote:latest

ARG EXPIRED_DATE=2030-09-30
RUN pip --no-cache-dir install -i https://pypi.tuna.tsinghua.edu.cn/simple 'pyarmor>=7.7.4, <8.0' \
  && pyarmor licenses --expired ${EXPIRED_DATE} r001 \
  && pyarmor obfuscate --recursive --output=/root/obfuscate --with-license licenses/r001/license.lic server.py \
  && rm -rf /root/repo
WORKDIR /root/obfuscate
